#ifndef DIFFUSION_LIMITED_AGGREGATION_OBSTACLE_CUH
#define DIFFUSION_LIMITED_AGGREGATION_OBSTACLE_CUH

struct Obstacle {
    int xTopLeft, yTopLeft;
    int recWidth, recHeight;
};

#endif // DIFFUSION_LIMITED_AGGREGATION_OBSTACLE_CUH
